_target_: src.models.tpp_module.TPPLitModule

defaults:
  - _self_
  - criterion: adaflood # [tpp, flood_tpp, iflood_tpp, adaflood_tpp]

optimizer:
  _target_: torch.optim.Adam
  _partial_: True
  lr: 0.0001
  weight_decay: 0.0001
  eps: 1e-05
  betas: [0.9, 0.999]

net:
  _target_: src.models.tpp.tpp_aux_network.IntensityFreePredictorWithAux
  name: 'if'
  d_model: 96
  num_components: 8
  num_classes: ${data.datasets.num_classes}
  activation:
    name: tanh
    in_features: ${model.net.d_model}

  aux_lr: 0.001
  aux_weight_decay: 0.001
  aux_d_model: 64
  aux_logit_path: ${paths.log_dir}/${data.datasets.dataset}_${model.net.name}_tpp_aux${data.aux_num}/seed${seed}/lr${model.net.aux_lr}_wd${model.net.aux_weight_decay}_mdim${model.net.aux_d_model}/aux${data.aux_num}_logits.pkl


