_target_: src.models.tpp_module.TPPLitModule

defaults:
  - _self_
  - criterion: adaflood_tpp # [tpp, flood_tpp, iflood_tpp, adaflood_tpp]

optimizer:
  _target_: torch.optim.Adam
  _partial_: True
  lr: 0.0001
  weight_decay: 0.0001
  eps: 1e-05
  betas: [0.9, 0.999]

net:
  _target_: src.models.tpp.tpp_aux_network.TransformerMixWithAux
  name: 'thp_mix'
  num_classes: ${data.datasets.num_classes}
  d_model: 64
  d_inner: 64
  n_layers: 2
  cattn_n_layers: 1
  n_head: 1
  d_k: 64
  d_v: 64
  dropout: 0.1
  attn_l: 0
  base_l: 0
  perm_invar: False
  use_avg: True
  share_weights: True
  attn_only: False
  concat: False
  num_latent: 64
  vi_method: None
  num_z_samples: 32
  compute_acc: True

  activation:
    name: tanh
    #name: snake
    in_features: ${model.net.d_model}
    trainable: True

  aux_lr: 0.001
  aux_weight_decay: 0.001
  aux_d_model: 64
  aux_logit_path: ${paths.log_dir}/${data.datasets.dataset}_${model.net.name}_tpp_aux${data.aux_num}/seed1/lr${model.net.aux_lr}_wd${model.net.aux_weight_decay}_mdim${model.net.aux_d_model}/aux${data.aux_num}_logits.pkl

    #aux_weights_dir: ${paths.log_dir}/${data.datasets.dataset}_${model.net.name}_tpp_signle_aux/seed1/lr${model.net.aux_lr}_wd${model.net.aux_weight_decay}/checkpoints
    #aux1_weights_dir: ${paths.log_dir}/${data.datasets.dataset}_${model.net.name}_tpp_aux1/seed1/lr${model.net.aux_lr}_wd${model.net.aux_weight_decay}_mdim${model.net.aux_d_model}/checkpoints
    #aux2_weights_dir: ${paths.log_dir}/${data.datasets.dataset}_${model.net.name}_tpp_aux2/seed1/lr${model.net.aux_lr}_wd${model.net.aux_weight_decay}_mdim${model.net.aux_d_model}/checkpoints

