_target_: src.models.al_module.ALModule

defaults:
  - _self_
  - cls_net: resnet18 # [simplenet, resnet18]

optimizer:
  _target_: torch.optim.SGD # Adam
  _partial_: true
  lr: 0.001
  momentum: 0.9
  nesterov: False
  weight_decay: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.MultiStepLR
  _partial_: true
  milestones: [100, 150]
  gamma: 0.1

