# Copyright (c) 2024-present, Royal Bank of Canada.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

_target_: src.models.components.criterion.FloodCLSLoss

num_classes: ${data.datasets.num_classes}
flood_level: 0.0

